# http://module-build.sourceforge.net/META-spec.html
name:         Wx-GLCanvas
version:      0.09
version_from: lib/Wx/GLCanvas.pm
installdirs:  site
author:       Mattia Barbon <mbarbon@cpan.org>
abstract:     interface to wxWidgets' OpenGL canvas
license:      perl
requires:
  Wx:                   0.57
  Wx::build::MakeMaker: 0.16
#build_requires:
no_index:
  directory:
    - inc
    - t
    - samples

# extras.
configure_requires:
  Wx::build::MakeMaker: 0.16
dynamic_config: 1

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.09, EUMM-6.54.
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
