# http://module-build.sourceforge.net/META-spec.html
name:         Wx-GLCanvas
version:      0.06
version_from: lib/Wx/GLCanvas.pm
installdirs:  site
author:       Mattia Barbon <mbarbon@cpan.org>
abstract: interface to wxWidgets' OpenGL canvas
license: perl
requires:
  Wx: 0.57
#build_requires:
no_index:
  directory:
    - t
    - samples

# extras.
dynamic_config: 1

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.07, EUMM-6.32.
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
